version: "3.9"

services:
  web:
    build: .
    command: sh -c "python manage.py collectstatic --noinput && gunicorn project.wsgi -b 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: prod.env
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
